#!/bin/bash

cd ..

if [ ! -d boost_graph_cookbook_1 ]; then
  git clone -b develop https://github.com/richelbilderbeek/boost_graph_cookbook_1
fi

if [ ! -d ConceptMap ]; then
  git clone -b develop https://github.com/richelbilderbeek/ConceptMap
fi

if [ ! -d plane ]; then
  git clone -b develop https://github.com/richelbilderbeek/plane
fi

if [ ! -d QtConceptMap ]; then
  git clone -b develop https://github.com/richelbilderbeek/QtConceptMap
fi

if [ ! -d QEventLogger ]; then
  git clone https://github.com/richelbilderbeek/QEventLogger
fi

if [ ! -d QtKeyboardFriendlyGraphicsView ]; then
  git clone -b develop https://github.com/richelbilderbeek/QtKeyboardFriendlyGraphicsView
fi

if [ ! -d RibiClasses ]; then
  git clone -b develop https://github.com/richelbilderbeek/RibiClasses
fi

if [ ! -d RibiLibraries ]; then
  git clone -b develop https://github.com/richelbilderbeek/RibiLibraries
fi

if [ ! -d StyleSheetSetter ]; then
  git clone -b develop https://github.com/richelbilderbeek/StyleSheetSetter
fi

git clone -b develop https://github.com/Microsoft/GSL
