#!/bin/bash

# $1: cmp filename
# $2: associations
function are_associations_in_file()
{
  filename="$1"
  associations="$2"
  text=`cat $filename`

  # echo "are_associations_in_file: filename: "$filename > are_associations_in_file.log
  # echo "are_associations_in_file: associations: "$associations >> are_associations_in_file.log
  # echo "are_associations_in_file: text: "$text >> are_associations_in_file.log

  i=1 
  while [ 1 ]; do
    s=`echo "$associations" | cut -d '|' -f "$i"`

    # echo "s: "$s >> are_associations_in_file.log

    does_contain=`contains "$text" "$s"`

    # echo "does_contain: "$does_contain >> are_associations_in_file.log

    if [[ $does_contain -eq "1" ]]; then echo "1"; return 0; fi
    i=$((i+1))
  done    

  echo "0"
  return 0
}