#!/bin/bash

function close_assessor_set_focal_question()
{
  id=`find_assessor_set_focal_question`
  if [ $id ]; then
    xdotool windowactivate $id sleep 0.2 key Escape sleep 1.0
  else
    (>&2 echo "Assessor 'set focal question' dialog cannot be found")
  fi
}