#!/bin/bash

function close_student_start()
{
  id=`find_student_start`
  if [ $id ]; then
    xdotool windowactivate $id sleep 0.2 key Escape sleep 1.0
  else
    (>&2 echo "Student start dialog cannot be found")
  fi
}