#!/bin/bash

function close_student_association()
{
  id=`find_student_association`
  if [ $id ]; then
    xdotool windowactivate $id sleep 0.2 key Escape sleep 1.0
  else
    (>&2 echo "Student association dialog cannot be found")
  fi
}