#!/bin/bash

function close_student_open_file_dialog()
{
  id=`find_student_open_file_dialog`
  if [ $id ]; then
    xdotool windowactivate $id sleep 0.2 key Escape sleep 1.0
  else
    (>&2 echo "Student open file dialog cannot be found")
  fi
}