#!/bin/bash

# contains(string, substring)
#
# Returns 1 if the specified string contains the specified substring,
# otherwise returns 0.
#
# From https://stackoverflow.com/a/8811800/3364162
contains() {
    string="$1"
    substring="$2"

    # echo "string: "$string > contains.log
    # echo "substring: "$substring >> contains.log

    if test "${string#*$substring}" != "$string"
    then
        # echo "substring is in string" >> contains.log
        echo "1"
    else
        # echo "substring is not in string" >> contains.log
        echo "0"
    fi
}
