#!/bin/bash

function create_focal_question()
{
  goto_assessor_set_focal_question
 
  sleep 1

  id=`find_assessor_set_focal_question`

  if [ $id ]; then
    # Type the word
    xdotool windowactivate $id type "$1"
    # Save
    xdotool windowactivate $id key Alt+s sleep 1.0
    # Find the save dialog
    id=`find_assessor_save_focal_question`
    if [ $id ]; then
    # Type filename
      xdotool windowactivate $id type "$2"
      sleep 1
      # OK
      xdotool windowactivate $id key Alt+Return sleep 1.0
      # Exits to assessor menu
      exit_assessor_menu
    else
      (>&2 echo "Save focal question dialog not created")
      # Exit
      exit_assessor_set_focal_question
    fi
  else
    (>&2 echo "Set focal question dialog not created")
  fi
}