#!/bin/bash

function create_focal_question()
{
  goto_assessor_set_focal_question
 
  sleep 1

  id=`find_assessor_set_focal_question`

  if [ $id ]; then
    echo "Type the focal question"
    xdotool windowactivate $id type "$1"
    echo "Save"
    xdotool windowactivate $id key Alt+s sleep 1.0
    echo "Find the save dialog"
    id=`find_assessor_save_focal_question`
    if [ $id ]; then
      echo "Type filename"
      xdotool windowactivate $id type "$2"
      sleep 1
      echo "Press OK using ALT+ENTER"
      xdotool windowactivate $id key Alt+Return sleep 1.0
      echo "Exits to assessor menu"
      exit_assessor_menu
    else
      (>&2 echo "Save focal question dialog not created")
      echo "Exit"
      exit_assessor_set_focal_question
    fi
  else
    echo "Exit"
    (>&2 echo "Set focal question dialog not created")
  fi
}