#!/bin/bash

# $1: cmp filename
function goto_student_menu()
{
  if [ ! -f $1 ]; then
    fail "Input file '"$1"' absent"
    return
  fi

  goto_student_open_file_dialog
 
  sleep 1

  id=`find_student_open_file_dialog`

  if [ $id ]; then
    # Type the filename, then Enter
    xdotool windowactivate $id key Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete 
    xdotool windowactivate $id type "$1"
    sleep 1
    xdotool windowactivate $id key Return
    sleep 1
  else
    (>&2 echo "Assessor menu not created")
  fi
}