#!/bin/bash

function goto_assessor_set_focal_question()
{
  goto_assessor_menu
 
  sleep 1

  id=`find_assessor_menu`

  if [ $id ]; then
    # Pick '2.'
    xdotool windowactivate $id sleep 0.2 key Alt+g sleep 1.0
  else
    (>&2 echo "Set focal question dialog not created")
  fi
}