#!/bin/bash

# $1: question
# $2: student name
# $3: cmp filename
# $4: associations
function save_student_associations()
{
  question="$1"
  student_name="$2"
  filename="$3"
  associations="$4"

  create_student_associations "$question" "$student_name" "$filename" "$associations"

  sleep 2

  # Press ALT-S
  id=`find_student_association`
  if [ $id ]; then
    # Save
    xdotool windowactivate $id key Alt+s
    sleep 1
  else
    (>&2 echo "Student association dialog not created")
  fi

  id=`find_save_cluster`
  if [ $id ]; then
    xdotool windowactivate $id key Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete Delete
    sleep 1
    xdotool windowactivate $id type $filename
    sleep 1
    xdotool windowactivate $id key Return
    sleep 1
  else
    (>&2 echo "Save concept map dialog not created")
    return
  fi

}