#!/bin/bash

cd ..
cd ..

for folder in BrainWeaver BrainWeaverRuffian QtConceptMap
do

  cd $folder

  echo "git folder: "$folder
  git checkout develop
  git pull
  git merge richel
  git push
  git checkout richel
  git pull
  git merge develop
  git push
  cd ..
done
