#!/bin/bash

cd ..
cd ..

for folder in BrainWeaver BrainWeaverRuffian boost_graph_cookbook_1 RibiClasses RibiLibraries StyleSheetSetter ConceptMap QtConceptMap QtKeyboardFriendlyGraphicsView plane
do

  cd $folder

  echo "git folder: "$folder
  git checkout master
  git pull
  git checkout develop
  git pull
  git checkout richel
  git pull

  git checkout master
  git merge develop
  git push

  git checkout develop
  git merge richel
  git push
  cd ..
done
