#!/bin/bash

cd ..
cd ..

for folder in Brainweaver boost_graph_cookbook_1 RibiClasses RibiLibraries StyleSheetSetter ConceptMap QtConceptMap QtKeyboardFriendlyGraphicsView plane
do

  cd $folder

  echo "git folder: "$folder
  git checkout master
  git pull
  git merge develop
  git push
  git checkout develop
  git pull
  git merge master
  git push
  cd ..
done
