#!/bin/bash

cd ..
cd ..

for folder in ConceptMap QtConceptMap BrainWeaver BrainWeaverRuffian boost_graph_cookbook_1 RibiClasses RibiLibraries StyleSheetSetter QtKeyboardFriendlyGraphicsView plane
do

  cd $folder

  echo "git folder: "$folder
  git add --all :/
  git commit -m "Brainweaver update"
  git pull
  git push

  cd ..
done
